"use client";

import { Bot, Check, CircleDollarSign, FlaskConical, Gauge, GitBranch, MessageSquare, Plus, Save, ThumbsDown, ThumbsUp, Timer, Workflow } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { MetricChart } from "@/components/metric-chart";
import { ErrorState, LoadingState } from "@/components/page-state";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { api } from "@/lib/api";
import type { AIOperationsSummary, AgentExecutionHistory, ModelRoute, PlaygroundRun, PromptVersion, User } from "@/lib/types";

type Tab = "overview"|"executions"|"prompts"|"routing"|"playground";
const field="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 outline-none focus:border-teal-400";

export default function AIOperationsPage(){
  const [summary,setSummary]=useState<AIOperationsSummary|null>(null),[executions,setExecutions]=useState<AgentExecutionHistory[]>([]),[prompts,setPrompts]=useState<PromptVersion[]>([]),[routes,setRoutes]=useState<ModelRoute[]>([]),[me,setMe]=useState<User|null>(null),[tab,setTab]=useState<Tab>("overview"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[playground,setPlayground]=useState<PlaygroundRun[]>([]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const user=await api<User>("/auth/me");const [overview,history]=await Promise.all([api<AIOperationsSummary>("/ai-ops/summary"),api<AgentExecutionHistory[]>("/ai-ops/executions")]);setMe(user);setSummary(overview);setExecutions(history);if(user.role==="admin"){const [promptData,routeData]=await Promise.all([api<PromptVersion[]>("/ai-ops/prompts"),api<ModelRoute[]>("/ai-ops/routes")]);setPrompts(promptData);setRoutes(routeData)}}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load AI operations")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
  async function feedback(id:string,rating:number){await api(`/ai-ops/executions/${id}/feedback`,{method:"POST",body:JSON.stringify({rating})});setNotice("Feedback recorded for agent quality metrics.");await load()}
  async function createPrompt(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);await api("/ai-ops/prompts",{method:"POST",body:JSON.stringify({agent_name:data.get("agent"),name:data.get("name"),content:data.get("content"),activate:true})});setNotice("New prompt version created and activated.");event.currentTarget.reset();await load()}
  async function activatePrompt(id:string){await api(`/ai-ops/prompts/${id}/activate`,{method:"POST"});setNotice("Prompt version activated.");await load()}
  async function saveRoute(event:FormEvent<HTMLFormElement>,agent:string){event.preventDefault();const data=new FormData(event.currentTarget);const provider=String(data.get("provider"));const model=String(data.get("model"));await api(`/ai-ops/routes/${agent}`,{method:"PUT",body:JSON.stringify({primary:{provider,model},fallbacks:[{provider:"openai",model:"gpt-4.1-mini"},{provider:"anthropic",model:"claude-sonnet-4-20250514"},{provider:"google",model:"gemini-2.5-flash"},{provider:"mock",model:"local-deterministic"}].filter(item=>item.provider!==provider)})});setNotice(`${agent} routing policy updated.`);await load()}
  async function runPlayground(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const candidates=String(data.get("providers")).split(",").map(provider=>({provider,model:provider==="mock"?"local-deterministic":provider==="openai"?"gpt-4.1-mini":provider==="anthropic"?"claude-sonnet-4-20250514":"gemini-2.5-flash"}));const result=await api<PlaygroundRun[]>("/ai-ops/playground",{method:"POST",body:JSON.stringify({agent_name:data.get("agent"),prompt:data.get("prompt"),candidates})});setPlayground(result);setNotice("Playground comparison completed without changing production workflows.")}
  if(loading)return <LoadingState rows={6}/>;if(error||!summary)return <ErrorState message={error||"AI operations unavailable"} retry={load}/>;const admin=me?.role==="admin";const tabs:Tab[]=admin?["overview","executions","prompts","routing","playground"]:["overview","executions"];
  return <div className="mx-auto max-w-7xl"><PageHeader eyebrow="P2 control plane" title="AI Operations & Reliability"/><div className="mb-6 flex gap-2 overflow-x-auto pb-1">{tabs.map(value=><Button key={value} variant={tab===value?"default":"outline"} onClick={()=>setTab(value)} className="capitalize">{value}</Button>)}</div>{notice&&<p role="status" className="mb-4 rounded-xl bg-emerald-400/10 p-3 text-emerald-300">{notice}</p>}
    {tab==="overview"&&<Overview data={summary}/>} {tab==="executions"&&<Executions items={executions} feedback={feedback}/>} {tab==="prompts"&&admin&&<Prompts items={prompts} create={createPrompt} activate={activatePrompt}/>} {tab==="routing"&&admin&&<Routing items={routes} save={saveRoute}/>} {tab==="playground"&&admin&&<Playground run={runPlayground} results={playground}/>}</div>;
}

function Overview({data}:{data:AIOperationsSummary}){const cards=[["Executions",data.total_executions,Bot],["Success rate",`${data.success_rate}%`,Gauge],["Avg duration",`${data.average_latency_ms} ms`,Timer],["Retries",data.retries,Workflow],["Evaluation",`${Math.round(data.average_evaluation_score*100)}%`,Check],["Monthly spend",`$${data.costs.monthly_spend_usd.toFixed(4)}`,CircleDollarSign]] as const;return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label,value,Icon])=><Card key={label} className="p-5"><Icon className="mb-4 text-teal-300"/><p className="text-3xl font-semibold text-white">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></Card>)}</section><section className="mt-5 grid gap-4 lg:grid-cols-2"><MetricChart title="Daily AI spend" data={data.costs.daily}/><MetricChart title="Error categories" data={data.error_categories}/></section><h2 className="mb-4 mt-8 text-lg font-semibold text-white">Agent reliability</h2><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{data.agents.map(item=><Card key={item.agent_name} className="p-5"><div className="flex justify-between"><Bot className="text-cyan-300"/><StatusBadge status={`${item.success_rate}% success`}/></div><h3 className="mt-4 font-semibold capitalize text-white">{item.agent_name} Agent</h3><p className="mt-2 text-sm text-slate-500">Avg {item.average_latency_ms} ms · {item.failed_runs} failures</p><p className="mt-1 text-xs text-slate-700">{item.input_tokens+item.output_tokens} tokens · ${item.estimated_cost_usd.toFixed(4)}</p></Card>)}</section><section className="mt-5 grid gap-4 lg:grid-cols-3"><Breakdown title="Spend by agent" items={data.costs.by_agent}/><Breakdown title="Spend by provider" items={data.costs.by_provider}/><Breakdown title="Spend by user" items={data.costs.by_user}/></section></>}
function Breakdown({title,items}:{title:string;items:Array<{label:string;input_tokens:number;output_tokens:number;cost_usd:number}>}){return <Card className="p-5"><h3 className="font-semibold text-white">{title}</h3><div className="mt-4 space-y-3">{items.length?items.map(item=><div key={item.label} className="flex justify-between gap-3 text-sm"><span className="capitalize text-slate-500">{item.label}</span><span className="text-slate-300">{item.input_tokens+item.output_tokens} tok · ${item.cost_usd.toFixed(4)}</span></div>):<p className="text-sm text-slate-600">No spend recorded.</p>}</div></Card>}
function Executions({items,feedback}:{items:AgentExecutionHistory[];feedback:(id:string,rating:number)=>void}){return <Card className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="border-b border-white/8 text-xs uppercase text-slate-600"><tr><th className="p-4">Agent/task</th><th>Provider/model</th><th>Status</th><th>Duration</th><th>Tokens</th><th>Cost</th><th>Eval</th><th>Retry/error</th><th className="pr-4">Feedback</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-b border-white/5"><td className="p-4"><p className="font-medium capitalize text-white">{item.agent_name}</p><p className="text-xs text-slate-600">{item.task} · prompt v{item.prompt_version||"—"}</p></td><td><p className="capitalize text-slate-300">{item.provider}</p><p className="text-xs text-slate-600">{item.model}</p></td><td><StatusBadge status={item.status}/></td><td>{item.latency_ms} ms</td><td>{item.input_tokens+item.output_tokens}</td><td>${item.estimated_cost_usd.toFixed(6)}</td><td>{item.evaluation_score===null?"—":`${Math.round(item.evaluation_score*100)}%`}</td><td><p>{item.retry_count} retries</p><p className="text-xs text-red-300">{item.error_category}</p></td><td className="pr-4"><div className="flex gap-1"><Button size="icon" variant="ghost" aria-label={`Good output ${item.id}`} onClick={()=>feedback(item.id,1)}><ThumbsUp size={15}/></Button><Button size="icon" variant="ghost" aria-label={`Bad output ${item.id}`} onClick={()=>feedback(item.id,-1)}><ThumbsDown size={15}/></Button></div></td></tr>)}</tbody></table></Card>}
function Prompts({items,create,activate}:{items:PromptVersion[];create:(event:FormEvent<HTMLFormElement>)=>void;activate:(id:string)=>void}){return <div className="grid gap-5 lg:grid-cols-[1fr_1.4fr]"><Card className="p-6"><h2 className="font-semibold text-white">Create prompt version</h2><form onSubmit={create} className="mt-5 space-y-4"><select aria-label="Prompt agent" name="agent" className={field}><option>research</option><option>email</option><option>report</option></select><input aria-label="Prompt version name" name="name" required placeholder="Version name" className={field}/><textarea aria-label="Prompt instructions" name="content" required minLength={10} placeholder="Prompt instructions" className={`${field} min-h-44`}/><Button><Plus size={15}/>Create and activate</Button></form></Card><div className="space-y-3">{items.map(item=><Card key={item.id} className="p-5"><div className="flex justify-between gap-4"><div><p className="text-xs uppercase text-teal-300">{item.agent_name} · v{item.version}</p><h3 className="mt-1 font-semibold text-white">{item.name}</h3></div>{item.active?<StatusBadge status="active"/>:<Button size="sm" variant="outline" onClick={()=>activate(item.id)}>Activate</Button>}</div><p className="mt-3 line-clamp-3 whitespace-pre-wrap text-sm text-slate-500">{item.content}</p><div className="mt-3 flex gap-4 text-xs text-slate-600"><span>{item.performance_metrics.executions||0} runs</span><span>{Math.round((item.performance_metrics.average_evaluation||0)*100)}% quality</span><span>{item.performance_metrics.open_rate||0}% opens</span></div></Card>)}</div></div>}
function Routing({items,save}:{items:ModelRoute[];save:(event:FormEvent<HTMLFormElement>,agent:string)=>void}){return <div className="grid gap-4 lg:grid-cols-3">{items.map(item=><Card key={item.id} className="p-6"><GitBranch className="text-teal-300"/><h2 className="mt-4 font-semibold capitalize text-white">{item.agent_name} Agent</h2><form onSubmit={event=>save(event,item.agent_name)} className="mt-5 space-y-3"><select aria-label={`${item.agent_name} primary provider`} name="provider" defaultValue={item.primary_provider} className={field}><option value="openai">OpenAI</option><option value="anthropic">Anthropic Claude</option><option value="google">Google Gemini</option><option value="mock">Mock</option></select><input aria-label={`${item.agent_name} primary model`} name="model" defaultValue={item.primary_model} className={field}/><Button size="sm"><Save size={14}/>Save route</Button></form><div className="mt-4 border-t border-white/8 pt-4"><p className="text-xs uppercase text-slate-600">Fallback chain</p>{item.fallback_order.map((fallback,index)=><p key={`${fallback.provider}-${index}`} className="mt-2 text-xs text-slate-500">{index+1}. {fallback.provider} · {fallback.model}</p>)}</div></Card>)}</div>}
function Playground({run,results}:{run:(event:FormEvent<HTMLFormElement>)=>void;results:PlaygroundRun[]}){return <div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><Card className="p-6"><FlaskConical className="text-teal-300"/><h2 className="mt-4 font-semibold text-white">Agent playground</h2><p className="mt-2 text-sm text-slate-500">Compare providers without changing production workflows.</p><form onSubmit={run} className="mt-5 space-y-4"><select aria-label="Playground agent" name="agent" className={field}><option>research</option><option>email</option><option>report</option></select><select aria-label="Playground providers" name="providers" className={field}><option value="mock">Mock</option><option value="openai,anthropic,google">OpenAI vs Claude vs Gemini</option><option value="mock,openai">Mock vs OpenAI</option></select><textarea aria-label="Playground prompt" name="prompt" required placeholder="Test prompt" className={`${field} min-h-40`}/><Button><FlaskConical size={15}/>Run comparison</Button></form></Card><div className="grid gap-3 sm:grid-cols-2">{results.length?results.map(item=><Card key={item.id} className="p-5"><div className="flex justify-between"><h3 className="font-semibold capitalize text-white">{item.provider}</h3><span className="text-xs text-slate-600">{item.latency_ms} ms</span></div><p className="mt-1 text-xs text-slate-600">{item.model} · {item.input_tokens+item.output_tokens} tokens</p><pre className="mt-4 max-h-64 overflow-auto whitespace-pre-wrap rounded-xl bg-slate-950 p-3 text-xs text-slate-400">{JSON.stringify(item.output_json,null,2)}</pre></Card>):<Card className="grid min-h-64 place-items-center p-8 text-center text-slate-600"><div><MessageSquare className="mx-auto mb-3"/>Run a prompt to compare outputs.</div></Card>}</div></div>}
