"use client";

import { Plus, UserRoundX, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { EmptyState, ErrorState, LoadingState } from "@/components/page-state";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { api } from "@/lib/api";
import type { Role, User } from "@/lib/types";

const field="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5";
export default function UsersPage(){const [items,setItems]=useState<User[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[open,setOpen]=useState(false);const load=useCallback(async()=>{setLoading(true);setError("");try{setItems(await api("/users"))}catch(e){setError(e instanceof Error?e.message:"Unable to load users")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);async function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);try{await api("/users",{method:"POST",body:JSON.stringify({full_name:data.get("full_name"),email:data.get("email"),password:data.get("password"),role:data.get("role")})});setOpen(false);setNotice("User invited successfully.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to invite user")}}async function update(id:string,changes:{role?:Role;active?:boolean}){try{await api(`/users/${id}`,{method:"PATCH",body:JSON.stringify(changes)});setNotice("User access updated.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update user")}}
  return <div className="mx-auto max-w-6xl"><PageHeader eyebrow="Access control" title="Users and roles"/><div className="mb-5 flex justify-end"><Button onClick={()=>setOpen(!open)}>{open?<X/>:<Plus/>}{open?"Close":"Invite user"}</Button></div>{notice&&<p role="status" className="mb-4 rounded-xl bg-emerald-400/10 p-3 text-emerald-300">{notice}</p>}{error&&<ErrorState message={error} retry={load}/>} {open&&<Card className="mb-5 p-6"><h2 className="mb-5 font-semibold text-white">Invite tenant user</h2><form onSubmit={invite} className="grid gap-4 md:grid-cols-2"><label className="text-sm">Full name<input required name="full_name" className={field}/></label><label className="text-sm">Email<input required name="email" type="email" className={field}/></label><label className="text-sm">Temporary password<input required name="password" type="password" minLength={12} className={field}/></label><label className="text-sm">Role<select name="role" className={field}><option value="agent_viewer">Agent viewer</option><option value="manager">Manager</option><option value="admin">Admin</option></select></label><Button>Invite user</Button></form></Card>} {loading?<LoadingState/>:items.length===0?<EmptyState title="No tenant users" detail="Invite the first workspace user."/>:<Card className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-white/8 text-xs uppercase text-slate-600"><tr><th className="p-4">User</th><th>Role</th><th>Status</th><th>Joined</th><th className="pr-4 text-right">Actions</th></tr></thead><tbody>{items.map(user=><tr key={user.id} className="border-b border-white/5"><td className="p-4"><p className="font-medium text-white">{user.full_name}</p><p className="text-xs text-slate-600">{user.email}</p></td><td><select aria-label={`Role for ${user.full_name}`} value={user.role} onChange={e=>update(user.id,{role:e.target.value as Role})} className="rounded-lg border border-white/10 bg-slate-950 px-2 py-1.5"><option value="admin">Admin</option><option value="manager">Manager</option><option value="agent_viewer">Agent viewer</option></select></td><td><StatusBadge status={user.active?"active":"disabled"}/></td><td className="text-xs text-slate-600">{new Date(user.created_at).toLocaleDateString()}</td><td className="pr-4 text-right"><Button size="sm" variant="outline" onClick={()=>update(user.id,{active:!user.active})}><UserRoundX size={14}/>{user.active?"Disable":"Enable"}</Button></td></tr>)}</tbody></table></Card>}</div>;
}
