"use client";

import { Download, Eye, RotateCcw, Search, X } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { EmptyState, ErrorState, LoadingState } from "@/components/page-state";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { api } from "@/lib/api";
import type { Report, ReportPreview, User } from "@/lib/types";

export default function ReportsPage(){const [items,setItems]=useState<Report[]>([]),[me,setMe]=useState<User|null>(null),[preview,setPreview]=useState<ReportPreview|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[search,setSearch]=useState(""),[date,setDate]=useState("");const load=useCallback(async()=>{setLoading(true);setError("");try{const query=search?`?search=${encodeURIComponent(search)}`:"";const [reports,user]=await Promise.all([api<Report[]>(`/reports${query}`),api<User>("/auth/me")]);setItems(reports);setMe(user)}catch(e){setError(e instanceof Error?e.message:"Unable to load reports")}finally{setLoading(false)}},[search]);useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[load]);const filtered=date?items.filter(item=>item.created_at.slice(0,10)===date):items;
  async function show(id:string){try{setPreview(await api(`/reports/${id}/preview`))}catch(e){setError(e instanceof Error?e.message:"Unable to preview report")}}async function regenerate(id:string){try{await api(`/reports/${id}/regenerate`,{method:"POST"});setNotice("Report regenerated successfully.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to regenerate report")}}
  return <div className="mx-auto max-w-6xl"><PageHeader eyebrow="Intelligence" title="Reports"/><div className="mb-5 grid gap-3 sm:grid-cols-[1fr_200px]"><label className="relative"><span className="sr-only">Search reports</span><Search className="absolute left-3 top-3 text-slate-600" size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Filter by lead or company" className="w-full rounded-xl border border-white/10 bg-slate-950 py-2.5 pl-10 pr-3"/></label><input aria-label="Filter by generated date" type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-xl border border-white/10 bg-slate-950 px-3"/></div>{notice&&<p role="status" className="mb-4 rounded-xl bg-emerald-400/10 p-3 text-emerald-300">{notice}</p>}{error&&<ErrorState message={error} retry={load}/>} {preview&&<Card className="mb-5 border-teal-400/20 p-6"><div className="flex justify-between gap-4"><div><p className="text-xs uppercase text-teal-300">Report preview</p><h2 className="mt-1 text-xl font-semibold text-white">{preview.title}</h2></div><Button variant="ghost" size="icon" aria-label="Close preview" onClick={()=>setPreview(null)}><X/></Button></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{Object.entries(preview.report).map(([key,value])=><div key={key} className="rounded-xl bg-slate-950 p-4"><p className="text-xs uppercase text-slate-600">{key.replaceAll("_"," ")}</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-300">{Array.isArray(value)?value.join(", "):String(value)}</p></div>)}</div></Card>} {loading?<LoadingState/>:filtered.length===0?<EmptyState title="No reports found" detail="Approve an agent draft or adjust the filters."/>:<div className="space-y-3">{filtered.map(item=><Card data-testid="report-card" key={item.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="flex-1"><h2 className="font-semibold text-white">{item.title}</h2><p className="mt-1 text-sm text-slate-500">Lead summary report · {Math.ceil(item.size_bytes/1024)} KB · {new Date(item.created_at).toLocaleString()}</p><div className="mt-2"><StatusBadge status={item.status}/></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>show(item.id)}><Eye size={16}/>Preview</Button>{me?.role!=="agent_viewer"&&<Button variant="outline" onClick={()=>regenerate(item.id)}><RotateCcw size={16}/>Regenerate</Button>}<Button asChild><a href={`/api/backend/reports/${item.id}/download`}><Download size={16}/>Download PDF</a></Button></div></Card>)}</div>}</div>;
}
