"use client";

import { KeyRound, Save, ShieldCheck } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { ErrorState, LoadingState } from "@/components/page-state";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { api } from "@/lib/api";
import type { TenantSettings } from "@/lib/types";

const field="mt-2 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 outline-none focus:border-teal-400";
export default function SettingsPage(){const [data,setData]=useState<TenantSettings|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await api("/settings"))}catch(e){setError(e instanceof Error?e.message:"Unable to load settings")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");const form=new FormData(event.currentTarget);try{const updated=await api<TenantSettings>("/settings",{method:"PUT",body:JSON.stringify({company_name:form.get("company_name"),llm_provider:form.get("llm_provider"),api_key:form.get("api_key")||null,whatsapp_enabled:form.get("whatsapp_enabled")==="on",email_enabled:form.get("email_enabled")==="on",n8n_webhook_url:form.get("n8n_webhook_url")||null,report_brand_name:form.get("report_brand_name")})});setData(updated);setNotice("Workspace settings saved and audited.")}catch(e){setError(e instanceof Error?e.message:"Unable to save settings")}finally{setSaving(false)}}
  return <div className="mx-auto max-w-5xl"><PageHeader eyebrow="Workspace administration" title="Settings"/>{notice&&<p role="status" className="mb-4 rounded-xl bg-emerald-400/10 p-3 text-emerald-300">{notice}</p>}{error&&<ErrorState message={error} retry={load}/>} {loading||!data?<LoadingState/>:<form onSubmit={save}><div className="grid gap-5 lg:grid-cols-2"><Card className="p-6"><h2 className="flex items-center gap-2 font-semibold text-white"><ShieldCheck className="text-teal-300" size={18}/>Tenant and branding</h2><label className="mt-5 block text-sm">Company name<input name="company_name" required defaultValue={data.company_name} className={field}/></label><label className="mt-4 block text-sm">Report brand name<input name="report_brand_name" required defaultValue={data.report_brand_name} className={field}/></label><label className="mt-4 block text-sm">n8n webhook URL<input name="n8n_webhook_url" type="url" defaultValue={data.n8n_webhook_url||""} className={field} placeholder="https://automation.example/webhook/…"/></label></Card><Card className="p-6"><h2 className="flex items-center gap-2 font-semibold text-white"><KeyRound className="text-teal-300" size={18}/>AI and delivery integrations</h2><label className="mt-5 block text-sm">LLM provider<select name="llm_provider" defaultValue={data.llm_provider} className={field}><option value="mock">Mock (safe mode)</option><option value="openai">OpenAI</option><option value="gemini">Gemini</option><option value="claude">Claude</option></select></label><label className="mt-4 block text-sm">Provider API key<input name="api_key" type="password" className={field} placeholder={data.api_key_configured?"Configured · enter to replace":"Not configured"}/><span className="mt-1 block text-xs text-slate-600">The UI never returns stored secret material.</span></label><label className="mt-5 flex min-h-12 items-center gap-3 rounded-xl border border-white/8 p-3"><input name="email_enabled" type="checkbox" defaultChecked={data.email_enabled}/><span><b className="block text-sm text-white">Email delivery</b><small className="text-slate-600">Still requires human approval before send</small></span></label><label className="mt-3 flex min-h-12 items-center gap-3 rounded-xl border border-white/8 p-3"><input name="whatsapp_enabled" type="checkbox" defaultChecked={data.whatsapp_enabled}/><span><b className="block text-sm text-white">WhatsApp delivery</b><small className="text-slate-600">Still requires human approval before send</small></span></label></Card></div><div className="mt-5 flex justify-end"><Button disabled={saving}><Save size={16}/>{saving?"Saving…":"Save settings"}</Button></div></form>}</div>;
}
