"use client";

import { Bell, ChevronDown, Command, Menu, Search, TriangleAlert, X } from "lucide-react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { navigation, Sidebar } from "@/components/sidebar";
import { ThemeToggle } from "@/components/theme-toggle";
import { api } from "@/lib/api";
import type { DashboardSummary, User } from "@/lib/types";
import { cn } from "@/lib/utils";

export function AppShell({children}:{children:React.ReactNode}){
  const pathname=usePathname(),router=useRouter();
  const [mobile,setMobile]=useState(false),[collapsed,setCollapsed]=useState(false),[searchOpen,setSearchOpen]=useState(false),[profileOpen,setProfileOpen]=useState(false),[me,setMe]=useState<User|null>(null),[summary,setSummary]=useState<DashboardSummary|null>(null);
  useEffect(()=>{setCollapsed(localStorage.getItem("orbitops-sidebar")==="collapsed");if(pathname!=="/login")void Promise.all([api<User>("/auth/me"),api<DashboardSummary>("/dashboard/summary")]).then(([user,data])=>{setMe(user);setSummary(data)}).catch(()=>{})},[pathname]);
  useEffect(()=>{function key(event:KeyboardEvent){if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setSearchOpen(value=>!value)}if(event.key==="Escape"){setSearchOpen(false);setProfileOpen(false);setMobile(false)}}addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[]);
  const visible=useMemo(()=>navigation.filter(([label,,,group])=>group!=="admin"||me?.role==="admin"||(label==="Audit logs"&&me?.role==="manager")),[me]);
  if(pathname==="/login")return <main className="min-h-screen">{children}</main>;
  function toggleCollapse(){setCollapsed(value=>{localStorage.setItem("orbitops-sidebar",value?"expanded":"collapsed");return !value})}
  async function signOut(){await fetch('/api/auth/logout',{method:'POST'});window.location.assign('/login')}
  return <div className="min-h-screen bg-[var(--bg)]"><Sidebar collapsed={collapsed} onCollapse={toggleCollapse} me={me} summary={summary}/>
    <header className={cn("sticky top-0 z-30 flex h-16 items-center gap-3 border-b hairline bg-[color-mix(in_srgb,var(--surface)_88%,transparent)] px-4 backdrop-blur-xl transition-[margin] lg:px-6",collapsed?"lg:ml-[76px]":"lg:ml-[248px]")}>
      <button aria-label={mobile?"Close navigation":"Open navigation"} onClick={()=>setMobile(!mobile)} className="grid size-10 place-items-center rounded-lg border hairline text-muted lg:hidden">{mobile?<X size={19}/>:<Menu size={19}/>}</button>
      <button onClick={()=>setSearchOpen(true)} className="hidden h-9 w-full max-w-[380px] items-center gap-2 rounded-lg border hairline bg-[var(--surface-subtle)] px-3 text-left text-sm text-muted md:flex"><Search size={15}/><span className="flex-1">Search leads, workflows, reports…</span><kbd className="flex items-center gap-0.5 rounded border hairline bg-[var(--surface)] px-1.5 py-0.5 text-[10px]"><Command size={10}/>K</kbd></button>
      <div className="ml-auto flex items-center gap-2"><button aria-label="Workflow alerts" className="relative hidden h-9 items-center gap-2 rounded-lg border hairline px-2.5 text-xs text-muted hover:bg-[var(--surface-subtle)] sm:flex"><TriangleAlert size={15} className="text-amber-500"/>{summary?.failed_workflows||0} alerts</button><ThemeToggle/><button aria-label="Notifications" className="relative grid size-9 place-items-center rounded-lg border hairline text-muted hover:bg-[var(--surface-subtle)]"><Bell size={16}/>{Boolean(summary?.pending_approvals)&&<i className="absolute right-2 top-2 size-1.5 rounded-full bg-amber-500"/>}</button>
        <div className="relative"><button onClick={()=>setProfileOpen(!profileOpen)} className="flex h-9 items-center gap-2 rounded-lg pl-1 pr-1.5 hover:bg-[var(--surface-subtle)]"><span className="grid size-8 place-items-center rounded-lg bg-gradient-to-br from-blue-500 to-indigo-500 text-xs font-bold text-white">{me?.full_name?.split(" ").map(part=>part[0]).join("").slice(0,2)||"OP"}</span><span className="hidden text-left xl:block"><b className="block max-w-32 truncate text-xs text-strong">{me?.full_name||"Loading"}</b><small className="block text-[10px] capitalize text-muted">{me?.role?.replace("_"," ")||"workspace"}</small></span><ChevronDown size={13} className="hidden text-muted xl:block"/></button>{profileOpen&&<div className="app-surface absolute right-0 top-11 w-56 rounded-xl border p-1.5"><div className="border-b hairline px-2.5 py-2"><p className="truncate text-xs font-semibold text-strong">{me?.email}</p><p className="mt-0.5 text-[10px] text-muted">OrbitOps Demo</p></div><Link href="/settings" onClick={()=>setProfileOpen(false)} className="mt-1 block rounded-lg px-2.5 py-2 text-sm hover:bg-[var(--surface-subtle)]">Workspace settings</Link><button onClick={signOut} className="w-full rounded-lg px-2.5 py-2 text-left text-sm text-[var(--danger)] hover:bg-[var(--surface-subtle)]">Sign out</button></div>}</div>
      </div>
    </header>
    {mobile&&<div className="fixed inset-0 z-50 lg:hidden"><button aria-label="Close navigation overlay" className="absolute inset-0 bg-slate-950/60 backdrop-blur-sm" onClick={()=>setMobile(false)}/><aside className="absolute inset-y-0 left-0 w-[86%] max-w-[320px] overflow-y-auto bg-[var(--sidebar)] p-4 text-slate-200 shadow-2xl"><div className="mb-5 flex items-center justify-between"><b className="text-white">OrbitOps</b><button aria-label="Close navigation" onClick={()=>setMobile(false)} className="grid size-10 place-items-center rounded-lg border border-white/10"><X size={18}/></button></div><div className="mb-4 rounded-xl border border-white/10 p-3 text-xs"><p className="font-semibold text-white">OrbitOps Demo</p><p className="mt-1 text-[#75839a]">Production workspace</p></div><nav aria-label="Mobile navigation" className="space-y-1">{visible.map(([label,href,Icon])=><Link key={href} href={href as never} onClick={()=>setMobile(false)} className="flex min-h-12 items-center gap-3 rounded-lg px-3 text-sm text-[#a5b1c2] hover:bg-white/5 hover:text-white"><Icon size={17}/>{label}</Link>)}</nav></aside></div>}
    {searchOpen&&<div role="dialog" aria-modal="true" aria-label="Global search" className="fixed inset-0 z-[60] flex items-start justify-center bg-slate-950/55 px-4 pt-[12vh] backdrop-blur-sm" onMouseDown={event=>{if(event.currentTarget===event.target)setSearchOpen(false)}}><div className="app-surface w-full max-w-xl overflow-hidden rounded-2xl border"><label className="flex items-center gap-3 border-b hairline px-4"><Search size={18} className="text-muted"/><input autoFocus aria-label="Search workspace" placeholder="Where do you want to go?" className="h-14 flex-1 bg-transparent text-sm text-strong outline-none"/><kbd className="rounded border hairline px-1.5 py-0.5 text-[10px] text-muted">ESC</kbd></label><div className="p-2"><p className="px-2 py-2 text-[10px] font-bold uppercase tracking-[.12em] text-muted">Quick navigation</p>{visible.slice(0,8).map(([label,href,Icon])=><button key={href} onClick={()=>{setSearchOpen(false);router.push(href)}} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm text-muted hover:bg-[var(--surface-subtle)] hover:text-[var(--text-strong)]"><Icon size={16}/>{label}<span className="ml-auto text-[10px]">Jump to</span></button>)}</div></div></div>}
    <main className={cn("min-h-[calc(100vh-4rem)] p-4 transition-[margin] sm:p-6 xl:p-8",collapsed?"lg:ml-[76px]":"lg:ml-[248px]")}>{children}</main>
  </div>;
}
