"use client";

import { Archive, Download, ExternalLink, Pencil, Play, Plus, Search, X } from "lucide-react";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { EmptyState, ErrorState, LoadingState } from "@/components/page-state";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { api } from "@/lib/api";
import type { Lead, User, Workflow } from "@/lib/types";

const input="mt-2 h-10 w-full rounded-lg border hairline bg-[var(--surface-subtle)] px-3 outline-none focus:border-[var(--brand)]";
export default function LeadsPage(){
  const [leads,setLeads]=useState<Lead[]>([]),[me,setMe]=useState<User|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[formOpen,setFormOpen]=useState(false),[editing,setEditing]=useState<Lead|null>(null),[saving,setSaving]=useState(false),[search,setSearch]=useState(""),[priority,setPriority]=useState("");
  const canEdit=me?.role==="admin"||me?.role==="manager";
  const load=useCallback(async()=>{setLoading(true);setError("");try{const query=new URLSearchParams();if(search)query.set("search",search);if(priority)query.set("priority",priority);const [items,user]=await Promise.all([api<Lead[]>(`/leads?${query}`),api<User>("/auth/me")]);setLeads(items);setMe(user)}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load leads")}finally{setLoading(false)}},[search,priority]);useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[load]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");const f=new FormData(event.currentTarget);const body={name:f.get("name"),company:f.get("company"),industry:f.get("industry")||null,website:f.get("website")||null,email:f.get("email")||null,phone:f.get("phone")||null,priority:f.get("priority")||undefined,attributes:{...(editing?.attributes||{}),intent_score:Number(f.get("intent_score")||0)}};try{if(editing)await api(`/leads/${editing.id}`,{method:"PATCH",body:JSON.stringify(body)});else await api("/leads",{method:"POST",body:JSON.stringify(body)});setNotice(editing?"Lead updated successfully.":"Lead created successfully.");setEditing(null);setFormOpen(false);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save lead")}finally{setSaving(false)}}
  async function start(lead:Lead){setError("");try{const run=await api<Workflow>("/workflows",{method:"POST",body:JSON.stringify({lead_id:lead.id})});setNotice(run.status==="waiting_approval"?`Agents completed. Approval is waiting for ${lead.company}.`:`Workflow status: ${run.status}`);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to start workflow")}}
  async function archive(lead:Lead){if(!window.confirm(`Archive ${lead.name} at ${lead.company}?`))return;await api(`/leads/${lead.id}`,{method:"DELETE"});setNotice("Lead archived.");await load()}
  return <div className="mx-auto max-w-[1480px]"><PageHeader eyebrow="Revenue operations" title="Leads" description="Qualify, assign, and move prospects through agent-powered workflows."/>
    <div className="mb-4 grid gap-3 sm:grid-cols-[1fr_180px_auto_auto]"><label className="relative"><span className="sr-only">Search leads</span><Search className="absolute left-3 top-3 text-muted" size={16}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search name or company" className="h-10 w-full rounded-lg border hairline bg-[var(--surface)] pl-9 pr-3 text-sm"/></label><select aria-label="Filter by priority" value={priority} onChange={event=>setPriority(event.target.value)} className="h-10 rounded-lg border hairline bg-[var(--surface)] px-3 text-sm"><option value="">All priorities</option><option>high</option><option>medium</option><option>low</option><option>unassessed</option></select><Button variant="outline"><Download size={15}/>Export</Button>{canEdit&&<Button onClick={()=>{setEditing(null);setFormOpen(!formOpen)}}>{formOpen?<X size={15}/>:<Plus size={15}/>} {formOpen?"Close":"Add lead"}</Button>}</div>
    {notice&&<p role="status" className="mb-4 rounded-lg border border-emerald-500/15 bg-emerald-500/8 p-3 text-sm text-emerald-500">{notice}</p>}{error&&<ErrorState message={error} retry={load}/>} {(formOpen||editing)&&<Card className="mb-5 p-5"><div className="mb-5"><p className="eyebrow">Lead record</p><h2 className="mt-1 text-lg font-semibold text-strong">{editing?"Edit lead":"Create lead"}</h2></div><form onSubmit={save} className="grid gap-4 md:grid-cols-2"><Field label="Lead name" name="name" required value={editing?.name}/><Field label="Company" name="company" required value={editing?.company}/><Field label="Industry" name="industry" value={editing?.industry}/><Field label="Website" name="website" type="url" value={editing?.website}/><Field label="Email" name="email" type="email" value={editing?.email}/><Field label="Phone" name="phone" value={editing?.phone}/><label className="text-xs font-medium text-muted">Priority<select className={input} name="priority" defaultValue={editing?.priority||"unassessed"}><option>unassessed</option><option>high</option><option>medium</option><option>low</option></select></label><label className="text-xs font-medium text-muted">Intent score (0–20)<input className={input} name="intent_score" type="number" min="0" max="20" defaultValue={String(editing?.attributes.intent_score||0)}/></label><div className="flex items-end gap-2"><Button disabled={saving}>{saving?"Saving…":"Save lead"}</Button>{editing&&<Button type="button" variant="outline" onClick={()=>setEditing(null)}>Cancel</Button>}</div></form></Card>}
    {loading?<LoadingState/>:leads.length===0?<EmptyState title="No leads found" detail="Create a lead or adjust the current filters."/>:<div className="table-shell overflow-x-auto"><table className="responsive-card-table min-w-[940px] text-left text-sm"><thead><tr><th>Lead</th><th>Score</th><th>Priority</th><th>Workflow</th><th>Approval</th><th>Last activity</th><th>Owner</th><th className="text-right">Actions</th></tr></thead><tbody>{leads.map(lead=><tr data-testid="lead-card" key={lead.id}><td><Link href={`/leads/${lead.id}`} className="font-semibold text-strong hover:text-[var(--brand)]">{lead.name}</Link><p className="mt-0.5 text-[11px] text-muted">{lead.company} · {lead.industry||"No industry"}</p></td><td data-label="Score"><span className="tabular font-semibold text-strong">{lead.score??"—"}</span></td><td data-label="Priority"><StatusBadge status={lead.priority}/></td><td data-label="Workflow"><StatusBadge status={lead.qualification_status||"new"}/></td><td data-label="Approval"><StatusBadge status={lead.qualification_status==="qualified"?"approved":"not requested"}/></td><td data-label="Last activity" className="text-xs text-muted">{new Date(lead.updated_at).toLocaleDateString()}</td><td data-label="Owner"><span className="inline-flex items-center gap-2 text-xs"><i className="grid size-6 place-items-center rounded-full bg-indigo-500/10 text-[9px] font-bold not-italic text-indigo-500">OP</i>Ops team</span></td><td><div className="flex justify-end gap-1"><Button asChild variant="outline" size="sm"><Link href={`/leads/${lead.id}`} aria-label={`Open ${lead.name}`}><ExternalLink size={14}/></Link></Button>{canEdit&&<><Button variant="outline" size="sm" aria-label={`Edit ${lead.name}`} onClick={()=>{setEditing(lead);setFormOpen(false)}}><Pencil size={14}/></Button><Button variant="outline" size="sm" aria-label={`Run agents for ${lead.name}`} onClick={()=>start(lead)}><Play size={14}/></Button><Button variant="ghost" size="sm" aria-label={`Archive ${lead.name}`} onClick={()=>archive(lead)}><Archive size={14}/></Button></>}</div></td></tr>)}</tbody></table></div>}
  </div>
}
function Field({label,name,required=false,type="text",value}:{label:string;name:string;required?:boolean;type?:string;value?:string|null}){return <label className="text-xs font-medium text-muted">{label}<input className={input} name={name} required={required} type={type} defaultValue={value||""}/></label>}
